# The Backend Connection to be used for the HTTP-Requests
backend:
  online: false
  prod: false
  host: ardas-legends.kekx.eu
  port: 8080

#Feature toggle: Each feature can be toggled individually, true = feature on, false = feature of
feature:
  stockpile: true
  rpchar: true
  monthly-resources: true
  hunting: true

hunting:
  hunt-prep-time: 7
  hunt-time: 30
  hunter-cooldown: 30
  travel-distance: 200 # Number of blocks you can move in one second before rollback
  countdown: [1, 2, 3, 4, 5, 10, 30]