# The Backend Connection to be used for the HTTP-Requests
backend:
  prod: false
  host: 'localhost' # PROD: ardas-legends.kekx.eu
  port: 8080

#Feature toggle: Each feature can be toggled individually, true = feature on, false = feature of
feature:
  stockpile: true
  rpchar: true