# The Backend Connection to be used for the HTTP-Requests
backend:
  online: false
  prod: true
  host: ardas-legends.kekx.eu
  port: 8080

#Feature toggle: Each feature can be toggled individually, true = feature on, false = feature of
feature:
  stockpile: true
  rpchar: true
  monthly-resources: true
  hunting: true

custom-recipe:
  #small-pouch: true
  dropper: true
  dispenser: true

hunting:
  hunt-prep-time: 7 # 120 (2minutes)
  hunt-time: 30 # 600 (10 minutes)
  hunt-range: 2000 # Maximal range for hunting someone
  hunter-cooldown: 30 # 1800 (30 minutes)
  travel-distance: 200 # Number of blocks you can move in one second before rollback
  countdown: [1, 2, 3, 4, 5, 10, 30]