name: Feature Request
description: Request a feature
title: "[Feature]: "
labels: ["feature-request"]
body: 
  - type: markdown
    attributes:
      value: Please be aware, that this Request is not guarantied to be accepted and worked on.
  - type: dropdown
    id: project-selection
    attributes: 
      label: Project
      description: For which Project is this request
      multiple: false
      options:
      - AL_Base_Plugin
      default: 0
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you, if we need more infomation
      placeholder: Your Discord ID
    validations:
      required: true
  
